### ISSUE TITLE
Consultas para as listas

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/listas#6]
- [x] Alunos de graduação
- [x] Alunos de pós-graduação
- [x] Docentes
- [x] Funcionários
- [x] 5 Listas de Graduação para cada curso de graduação (Arthur)
- [x] 23 Listas para Pós-Graduação para cada programa 
- [ ] 23 para docentes credenciados para Pós-Graduação para cada programa
- [ ] 23 Listas para Ex-alunos Pós-Graduação para cada programa
- [ ] Funcionários, Alunos de graduação, pós e Docentes Ativos e Aposentados do Departamento de Filosofia
 - [x] coordenadores de pós
- [ ] CCPS -  é uma por programa? 
- [x] 1 para pós doutorados ativos
- [x] 1 lista para alunos estrangeiros (Nelson)
- [x] 1 Chefes administrativos (Ricardo)
- [x] 1 Chefe de departamento (Ricardo)
- [x] 1 Docentes Aposentados (Gabriela)
- [x] 11 Docentes Aposentados por Departamento (Gabriela)
- [x] 11 Docentes Ativos de cada departamento (Augusto)
- [x] 1 Secretários(as) departamento (Ricardo)
- [x] 11 Funcionários Ativos de cada departamento (Augusto)
- [x] 1 - Membros da Congregação (Augusto)
- [x] 1 - Membros do CTA (Augusto)
- [ ] 1 - Membros da Comissão de Coordenadora de Programa (Nelson)
- [x] 1 - Membros da Comissão de Cultura e Extensão (está nos sistemas USP?)
- [x] 1 - Funcionários da Biblioteca (Arthur)
- [x] 1 - Docentes que estão oferecendo disciplina de graduação neste semestre (Nelson)
- [x] 1 - Docentes que estão oferecendo disciplina de pós-graduação neste semestre (Nelson)
- [x] 1 - Lista para Estagiários (Gabriela)
- [x] 1 - Funcionários  e Estagiários da Seção Técnica de Informática (Thiago)

**Comment by FilosoDev** [comment]
Docentes que estão oferecendo disciplina de graduação neste semestre - ok

**Comment by FilosoDev** [comment]
Membros da Comissão de Cultura e Extensão -ok

**Comment by FilosoDev** [comment]
1 para pós doutorados ativos - ok

**Comment by thiagogomesverissimo** [comment]
> 1 para pós doutorados ativos - ok

nice

**Comment by FilosoDev** [comment]
Ex-alunos da Graduação - ok

**Comment by gabrielareisg** [comment]
coordenadores de pós - OK

**Comment by gabrielareisg** [comment]
Docentes que estão oferecendo disciplina de pós-graduação neste semestre - ok
